# Generated by Django 5.0.6 on 2024-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepayment',
            name='auto_pay_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedulepayment',
            name='account',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
