# Generated by Django 5.0.6 on 2024-06-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedulepayment_auto_pay_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('schedule_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulepayment')),
            ],
        ),
    ]
