# Generated by Django 5.0.6 on 2024-06-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_paidpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulepayment')),
            ],
        ),
    ]
