# Generated by Django 5.0.6 on 2024-06-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('status', models.CharField(max_length=16)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulepayment')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
