# Generated by Django 5.0.6 on 2024-06-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_transferreceipt_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.CharField(max_length=60, unique=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulepayment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('recipients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.transferrecipient')),
            ],
        ),
        migrations.DeleteModel(
            name='TransferReceipt',
        ),
    ]
