# Generated by Django 5.0.6 on 2024-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_schedulepayment_auto_pay_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepayment',
            name='amount',
            field=models.CharField(default='60000', help_text='Must greater than 0 and must not have a letter preceded', max_length=7),
        ),
    ]
