# Generated by Django 5.0.6 on 2024-06-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedulepayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterWaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trsc_id', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fw_transactions', to='schedule.schedulepayment')),
            ],
        ),
    ]
