# Generated by Django 5.0.6 on 2024-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_flutterwavetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepayment',
            name='bank_code',
            field=models.CharField(max_length=10),
        ),
    ]
