# Generated by Django 5.0.6 on 2024-06-07 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_schedulepayment_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidpayment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
